name: Automatic Driving Academy
favicon: null
layout_spectrum: 0.24143
typography_spectrum: 0.3314181799069047
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8f9ca2'
    - '#5b696a'
    - '#fbfbfb'
    - '#bcccdb'
  brandStrength: 0.9729109406471252
  lightness: 0.9012307929806411
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
