name: Automatic Driving Academy
favicon: null
layout_spectrum: 0.7088815772440284
typography_spectrum: 0.3314181799069047
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9729109406471252
  lightness: 0.9012307929806411
  saturation: 0.4444686302449554
  rhythmicContrast: 0.8324595333542675
purpose: []
